# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventParticipants',
            new_name='EventParticipant',
        ),
    ]
