# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 9, 35, 26, 951540, tzinfo=utc), verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 9, 35, 26, 951540, tzinfo=utc), verbose_name='modification date'),
        ),
    ]
